model_name_or_path: prm-clinic/output/Llama-8B_Instruct_lr_3e-5/checkpoint-685
special_tokens_file: prm-clinic/config/special_token.json
input_csv_file: prm-clinic/data/test_set_A_prefer/A_Prefer.csv
output_file: prm_project/results/llama_clinic/llama_clinic_test_temp.json
